export interface Competitor {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  pricing: string;
  features: { name: string; quotemate: boolean | string; competitor: boolean | string }[];
  summary: string;
}

export const competitors: Competitor[] = [
  {
    slug: 'tradify',
    name: 'Tradify',
    tagline: 'Compare quoting features, pricing, and ease of use for Australian tradies.',
    description: 'Tradify is a job management platform for trade businesses covering quoting, scheduling, timesheets, and invoicing.',
    pricing: 'Tradify starts at $35/user/month with per-user pricing that scales up for teams.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: false },
      { name: 'Real-time supplier pricing', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Job scheduling', quotemate: true, competitor: true },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: true },
      { name: 'Google Calendar sync', quotemate: true, competitor: 'Internal calendar only' },
      { name: 'On-site job photos with annotation', quotemate: true, competitor: true },
      { name: 'On-site job checklists', quotemate: true, competitor: true },
      { name: 'Automated quote follow-ups (day 3 / 7 / 14)', quotemate: true, competitor: 'Manual reminders' },
      { name: 'Timesheets', quotemate: false, competitor: true },
      { name: 'Offline mode', quotemate: true, competitor: false },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Flat pricing (no per-user fees)', quotemate: '$49/month', competitor: '$35/user/month' },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'QuoteMate covers the same job management Tradify is known for — 9-stage pipeline, scheduling, on-site photos, checklists — and pulls ahead on quoting speed with AI-generated materials lists and live Australian supplier pricing. Tradify still wins for teams that need timesheets and crew management, but for sole traders and small crews QuoteMate gets you everything you need on a flat $49/month with no per-user pricing.',
  },
  {
    slug: 'servicem8',
    name: 'ServiceM8',
    tagline: 'See how QuoteMate and ServiceM8 compare for quoting and invoicing.',
    description: 'ServiceM8 is a field service management app covering job management, quoting, scheduling, invoicing, and client communication.',
    pricing: 'ServiceM8 plans range from $0 to $379/month depending on job volume and features.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: false },
      { name: 'Real-time supplier pricing', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Job scheduling', quotemate: 'With Google Calendar sync', competitor: 'Scheduling & dispatch' },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: true },
      { name: 'On-site job photos with annotation', quotemate: true, competitor: true },
      { name: 'On-site job checklists', quotemate: true, competitor: true },
      { name: 'Automated quote follow-ups (day 3 / 7 / 14)', quotemate: true, competitor: 'Workflow add-on' },
      { name: 'Client communication (SMS/email)', quotemate: 'Share via SMS/email/WhatsApp', competitor: true },
      { name: 'Offline mode', quotemate: true, competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Simple flat pricing', quotemate: '$49/month', competitor: '$0–$379/month' },
      { name: 'Australian supplier integration', quotemate: 'Major suppliers', competitor: false },
    ],
    summary: 'ServiceM8 is built for field service businesses with complex dispatch and large crews. QuoteMate covers the same core job management — pipeline, scheduling, on-site photos, checklists — but is purpose-built for quoting: describe any job, get an AI-generated materials list with live supplier pricing, schedule it to Google Calendar, send the quote, and chase it automatically — all for a simple flat rate.',
  },
  {
    slug: 'fergus',
    name: 'Fergus',
    tagline: 'Compare QuoteMate and Fergus for tradie quoting and job management.',
    description: 'Fergus is a job management platform designed for trade businesses, offering quoting, scheduling, timesheets, purchase orders, and invoicing.',
    pricing: 'Fergus pricing starts at $55/month for basic features, scaling up for larger teams.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: false },
      { name: 'Real-time supplier pricing', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Job scheduling', quotemate: true, competitor: true },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: true },
      { name: 'Google Calendar sync', quotemate: true, competitor: 'Internal calendar only' },
      { name: 'On-site job photos with annotation', quotemate: true, competitor: true },
      { name: 'On-site job checklists', quotemate: true, competitor: true },
      { name: 'Automated quote follow-ups', quotemate: 'Built in (day 3 / 7 / 14)', competitor: 'Manual' },
      { name: 'Purchase orders', quotemate: 'Reece integration', competitor: true },
      { name: 'Offline mode', quotemate: true, competitor: false },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Flat pricing', quotemate: '$49/month', competitor: 'From $55/month' },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'Fergus offers deep job management with detailed job costing across many suppliers. QuoteMate matches it on pipeline, scheduling, on-site photos and checklists, then pulls ahead on speed — AI material suggestions, real-time pricing, and purchase orders straight to Reece — in under 2 minutes per quote, at about half the monthly cost.',
  },
  {
    slug: 'chatgpt',
    name: 'ChatGPT (and other AI chatbots)',
    tagline: 'Why ChatGPT, Gemini and Claude can\'t replace a real quoting app for Australian tradies.',
    description: 'ChatGPT, Google Gemini, Microsoft Copilot, and Anthropic Claude are general-purpose AI chatbots. Tradies sometimes paste a job description in and ask for a "quote", but the result is a chat reply — not a branded PDF, not an invoice, and not grounded in current Australian supplier pricing.',
    pricing: 'ChatGPT Plus, Gemini Advanced, and Claude Pro are each ~$30 AUD/month — and you still need a separate quoting app to actually send the quote.',
    features: [
      { name: 'Generates a job description', quotemate: 'AI-assisted, voice-to-text', competitor: true },
      { name: 'Live, accurate supplier prices (Bunnings, Reece, Tradelink, etc.)', quotemate: true, competitor: 'Hallucinated / outdated' },
      { name: 'Consistent output between runs', quotemate: 'Reusable templates', competitor: 'Different every time' },
      { name: 'Branded PDF quote with your logo & ABN', quotemate: true, competitor: false },
      { name: 'Convert quote to invoice in one tap', quotemate: true, competitor: false },
      { name: 'Customer can accept the quote from email', quotemate: true, competitor: false },
      { name: 'Take card payment on-site (tap-to-pay)', quotemate: true, competitor: false },
      { name: 'Send Australian payment links (PayID, BPAY, bank transfer)', quotemate: true, competitor: false },
      { name: 'Push to Xero', quotemate: true, competitor: false },
      { name: 'Auto GST & ABN handling', quotemate: 'Built in', competitor: 'Manual, prone to error' },
      { name: 'Track sent / accepted / paid status', quotemate: true, competitor: false },
      { name: 'Works offline on remote sites', quotemate: true, competitor: false },
      { name: 'Pricing', quotemate: 'Free or $49/month Pro', competitor: '~$30/month + still need a quoting app' },
    ],
    summary: 'A general-purpose chatbot can help you brainstorm a job description, but it can\'t produce a quote you can stand behind on a contract. The prices are hallucinated, the output changes every time you ask, and there\'s no PDF, no payment, and no Xero. QuoteMate uses AI in the same way (describe a job, get a materials list) but grounds every line item in live Australian supplier pricing, produces a branded PDF, and gives you one-tap invoicing, payment, and Xero sync. If you want AI to help you quote, use AI built into a quoting app — not a chatbot.',
  },
  {
    slug: 'spreadsheets',
    name: 'Excel & Google Sheets',
    tagline: 'See why a spreadsheet quote leaks money on every job.',
    description: 'Many tradies still quote in Excel, Google Sheets, or Numbers. It works for the first 10 jobs, but it doesn\'t scale: prices go stale, GST gets miscalculated, the file lives on one laptop, and you can\'t take payment from a spreadsheet.',
    pricing: 'Excel ~$9.95/month for Microsoft 365, Google Sheets free with a Google account.',
    features: [
      { name: 'Branded PDF quotes', quotemate: true, competitor: 'Manual setup' },
      { name: 'AI material list generation', quotemate: true, competitor: false },
      { name: 'Live supplier pricing (auto-updates)', quotemate: true, competitor: false },
      { name: 'Reusable templates', quotemate: 'Built in', competitor: 'Copy/paste a file' },
      { name: 'Quote-to-invoice conversion', quotemate: 'One tap', competitor: 'Manual rewrite' },
      { name: 'Job pipeline (inquiry to paid)', quotemate: '9 stages, auto-timestamped', competitor: false },
      { name: 'Job scheduling with calendar sync', quotemate: true, competitor: false },
      { name: 'On-site job photos with annotation', quotemate: true, competitor: false },
      { name: 'Automated quote follow-ups', quotemate: true, competitor: false },
      { name: 'Track sent / accepted / paid', quotemate: true, competitor: false },
      { name: 'GST & ABN handling', quotemate: 'Automatic', competitor: 'Manual formulas' },
      { name: 'Online quote acceptance', quotemate: true, competitor: false },
      { name: 'Take card payment on-site', quotemate: true, competitor: false },
      { name: 'Xero integration', quotemate: 'One-tap sync', competitor: 'Manual export' },
      { name: 'Works on phone on-site', quotemate: 'Native app', competitor: 'Awkward on mobile' },
    ],
    summary: 'A spreadsheet is fine until you realise your prices are six months stale, your last quote went out without GST, and your customer has nowhere to pay it. QuoteMate gives you all the flexibility of a spreadsheet (custom line items, your own labour rates, your own markup) but adds AI material generation, live supplier pricing, branded PDFs, online acceptance, payment links, and Xero sync. Tradies who switch from spreadsheets typically save 1–3 hours per quote and start charging GST correctly.',
  },
  {
    slug: 'invoice2go',
    name: 'Invoice2go',
    tagline: 'Compare quoting and invoicing features between QuoteMate and Invoice2go.',
    description: 'Invoice2go is a general-purpose invoicing app used across many industries, offering estimates, invoices, and payment tracking.',
    pricing: 'Invoice2go starts at $5.99/month for basic invoicing, up to $39.99/month for the premium plan.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: false },
      { name: 'Real-time supplier pricing', quotemate: true, competitor: false },
      { name: 'Trade-specific templates', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Payment tracking', quotemate: true, competitor: true },
      { name: 'Job management (9-stage pipeline)', quotemate: true, competitor: false },
      { name: 'Job scheduling with Google Calendar sync', quotemate: true, competitor: false },
      { name: 'On-site job photos with annotation', quotemate: true, competitor: false },
      { name: 'On-site job checklists', quotemate: true, competitor: false },
      { name: 'Automated quote follow-ups', quotemate: true, competitor: false },
      { name: 'Offline mode', quotemate: true, competitor: false },
      { name: 'Built for Australian tradies', quotemate: true, competitor: false },
      { name: 'GST calculations', quotemate: 'Automatic', competitor: 'Manual setup' },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
    ],
    summary: 'Invoice2go handles invoicing well across many industries but stops at the invoice. QuoteMate covers the full job lifecycle — quoting with AI material suggestions and live supplier pricing, scheduling, on-site photos and checklists, automated quote follow-ups, and invoicing — all built around how Australian tradies actually work.',
  },
  {
    slug: 'aroflo',
    name: 'AroFlo',
    tagline: 'Compare QuoteMate and AroFlo for tradie quoting, supplier pricing, and job management.',
    description: 'AroFlo is an Australian-built, end-to-end field service platform for established trade and commercial businesses, covering quoting, scheduling, timesheets, inventory, project management, and deep supplier integrations.',
    pricing: 'AroFlo uses per-user pricing (roughly $45–$77/user/month across Standard and Premium, 3-user minimum on the full product) plus one-time onboarding fees commonly $899–$2,900. A free AroFloGo self-service tier exists for micro operators.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: 'New (Lightning add-on)' },
      { name: 'Live Australian supplier pricing', quotemate: 'Bunnings, Reece, Tradelink', competitor: '600+ connected suppliers' },
      { name: 'Direct purchase-order ordering to suppliers', quotemate: 'Reece integration', competitor: true },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Job scheduling', quotemate: 'With Google Calendar sync', competitor: 'Advanced dispatch' },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: true },
      { name: 'Projects, Gantt & inventory', quotemate: false, competitor: true },
      { name: 'SWMS / compliance forms', quotemate: false, competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Offline mode', quotemate: true, competitor: 'Limited' },
      { name: 'Free plan available', quotemate: true, competitor: 'AroFloGo only' },
      { name: 'One-time setup / onboarding fee', quotemate: 'None', competitor: '$899–$2,900' },
      { name: 'Flat pricing (no per-user fees)', quotemate: '$49/month', competitor: 'Per-user + minimum seats' },
    ],
    summary: 'AroFlo is one of the deepest Australian platforms for established, process-heavy trade and commercial operations — its live supplier catalogues with direct purchase-order ordering are genuinely more advanced than most. But it is priced and built for teams with dedicated admin, with per-user fees and four-figure onboarding. QuoteMate targets the sole trader and small crew AroFlo steers toward its lighter product: the same fast AI quoting with live Bunnings, Reece and Tradelink pricing, on a flat $49/month with no setup fee and a free plan.',
  },
  {
    slug: 'buildxact',
    name: 'Buildxact',
    tagline: 'Compare QuoteMate and Buildxact for quoting, estimating, and live supplier pricing.',
    description: 'Buildxact is an Australian construction estimating and job-management platform for residential builders and renovators, with digital takeoff from plans, live supplier catalogues, and an AI estimating assistant.',
    pricing: 'Buildxact starts at $169/month (1 user, or $133/month billed annually), scaling to $279 and $439/month for larger teams, with extra users added per plan. 14-day free trial; no free plan.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: 'Blu AI assistant' },
      { name: 'Live Australian supplier pricing', quotemate: 'Bunnings, Reece, Tradelink', competitor: 'Bunnings, Mitre 10, Dahlsens' },
      { name: 'Plumbing suppliers (Reece / Tradelink)', quotemate: true, competitor: false },
      { name: 'Digital takeoff from plans', quotemate: false, competitor: true },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Mobile-first quoting on site', quotemate: 'Native app', competitor: 'Desktop-first' },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: 'Job management' },
      { name: 'Square tap-to-pay on-site', quotemate: true, competitor: false },
      { name: 'Offline mode', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
      { name: 'Flat pricing', quotemate: '$49/month', competitor: 'From $169/month' },
    ],
    summary: 'Buildxact is the one estimating tool that genuinely matches QuoteMate on live Australian supplier pricing plus AI — but it is built for residential builders pricing whole houses off plans, is desktop-first, and costs from $169/month with a real learning curve. QuoteMate is built for the tradie who needs a professional quote before leaving the driveway: describe the job by voice, get an AI materials list priced against live Bunnings, Reece and Tradelink rates, and send it from your phone. For plumbers and gas fitters especially, QuoteMate covers Reece and Tradelink where Buildxact does not.',
  },
  {
    slug: 'jobber',
    name: 'Jobber',
    tagline: 'Compare QuoteMate and Jobber for Australian tradie quoting and getting paid.',
    description: 'Jobber is a Canadian field-service management platform for small home-service businesses, covering quoting, scheduling, invoicing, a client portal, and payments in supported countries.',
    pricing: 'Jobber runs from US$29/user/month (Core, billed annually) up to US$599/month on higher tiers, with extra users at US$29/month each and paid add-ons — billed in US dollars.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: 'Copilot (coach, not takeoff)' },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'Native in-person payments in Australia', quotemate: 'Square tap-to-pay', competitor: false },
      { name: 'Australian GST & ABN handling', quotemate: 'Automatic', competitor: 'Manual setup' },
      { name: 'Priced in Australian dollars', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Job scheduling & dispatch', quotemate: 'Google Calendar sync', competitor: true },
      { name: 'Client self-service portal', quotemate: 'Online acceptance', competitor: true },
      { name: 'Recurring job automation', quotemate: false, competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
      { name: 'Flat pricing (no per-user fees)', quotemate: '$49/month', competitor: '+US$29/user' },
    ],
    summary: 'Jobber is a polished, mature platform for small home-service crews and is genuinely strong on scheduling, recurring work, and its client portal. But it is built for North America: it has no native in-person payments in Australia, bills in US dollars, and GST is a manual setup. QuoteMate is Australian by design — AUD pricing, automatic GST, Xero sync, live local supplier pricing, and Square tap-to-pay that actually works here — so an Aussie tradie can quote and get paid on the doorstep without the currency and tax workarounds Jobber requires.',
  },
  {
    slug: 'simpro',
    name: 'simPRO',
    tagline: 'Compare QuoteMate and simPRO for tradie quoting, pricing, and complexity.',
    description: 'simPRO is an Australian-built job and project management platform for mid-size and commercial trade contractors, with deep estimating, inventory, scheduling, and job costing.',
    pricing: 'simPRO publishes no public pricing. It is quoted per user (commonly several hundred dollars a month for a small team) with a significant one-off implementation fee and multi-year commitments. No free plan.',
    features: [
      { name: 'AI-powered quoting', quotemate: true, competitor: 'AI estimating' },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: 'Supplier catalogues (setup-heavy)' },
      { name: 'Fast quoting from a job description', quotemate: 'Under 2 minutes', competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Multi-crew dispatch & scheduling', quotemate: false, competitor: true },
      { name: 'Inventory & warehouse management', quotemate: false, competitor: true },
      { name: 'Detailed job costing', quotemate: false, competitor: true },
      { name: 'Self-serve setup (no onboarding project)', quotemate: true, competitor: false },
      { name: 'Transparent public pricing', quotemate: true, competitor: false },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
      { name: 'Flat pricing (no per-user fees)', quotemate: '$49/month', competitor: 'Quoted per user + setup' },
    ],
    summary: 'simPRO is a powerful platform for mid-size and commercial contractors that need multi-crew dispatch, inventory, and detailed job costing at scale — and it is priced and onboarded accordingly, with quoted per-user fees, a large upfront implementation, and multi-year commitments. For a sole trader or small crew that is overkill. QuoteMate is the opposite: sign up today, quote a job in under two minutes with AI and live Australian supplier pricing, and pay a flat $49/month with no setup fee. When you grow into a large commercial operation, simPRO makes sense; until then it is more than you need.',
  },
  {
    slug: 'servicetitan',
    name: 'ServiceTitan',
    tagline: 'Compare QuoteMate and ServiceTitan for Australian tradie quoting and cost.',
    description: 'ServiceTitan is a US enterprise field-service platform for mid-market and large residential and commercial contractors, covering dispatch, CRM, sales, payments, marketing, and reporting.',
    pricing: 'ServiceTitan is quoted per technician (commonly US$250–500/tech/month) on annual contracts with a one-time onboarding fee often between US$5,000 and US$50,000. Built for fleets of 20+ technicians; no free plan.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: 'Enterprise sales tools' },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'Australian GST & ABN handling', quotemate: 'Automatic', competitor: 'Limited AU localisation' },
      { name: 'Native Xero integration', quotemate: true, competitor: 'Limited / secondary' },
      { name: 'Self-serve setup (no onboarding project)', quotemate: 'Same day', competitor: '6–12 month onboarding' },
      { name: 'Built for sole traders & small crews', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Enterprise dispatch & reporting', quotemate: false, competitor: true },
      { name: 'No lock-in contract', quotemate: true, competitor: 'Annual, exit fees' },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
      { name: 'Flat pricing', quotemate: '$49/month', competitor: 'US$250–500/tech/month' },
    ],
    summary: 'ServiceTitan is an enterprise operating system for large contractors with fleets of technicians and dedicated back-office staff. Its depth is real, and so is its cost: quoted per technician in US dollars, with a five-figure implementation, annual contracts, and a six-to-twelve-month onboarding. For an Australian sole trader or small crew it is the wrong tool at roughly a hundred times the price. QuoteMate is built for that tradie — Australian pricing and GST, live local supplier pricing, Square tap-to-pay, and a flat $49/month you can start today with no contract.',
  },
  {
    slug: 'housecallpro',
    name: 'Housecall Pro',
    tagline: 'Compare QuoteMate and Housecall Pro for Australian tradie quoting.',
    description: 'Housecall Pro is a US field-service management app for small and mid-size home-service businesses, covering estimates, scheduling, dispatch, invoicing, payments, and marketing.',
    pricing: 'Housecall Pro runs from US$59/month (1 user) to US$299/month (up to 8 users, then +US$35/user), priced in US dollars and focused on the United States and Canada.',
    features: [
      { name: 'Available to Australian tradies', quotemate: true, competitor: 'US & Canada only' },
      { name: 'Australian GST & ABN handling', quotemate: 'Automatic', competitor: false },
      { name: 'Xero integration', quotemate: true, competitor: false },
      { name: 'Priced in Australian dollars', quotemate: true, competitor: false },
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: 'AI for admin / calls' },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'In-person payments in Australia', quotemate: 'Square tap-to-pay', competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Scheduling & dispatch', quotemate: 'Google Calendar sync', competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'Housecall Pro is a capable all-in-one for US and Canadian home-service businesses, but for an Australian tradie it is largely unusable out of the box: no Australian sign-up, no GST, no Xero, US-dollar pricing, and payment rails that do not operate here. QuoteMate is built for Australia from the ground up — automatic GST and ABN, Xero sync, live Bunnings, Reece and Tradelink pricing, and Square tap-to-pay on site — with a free plan and flat $49/month Pro. It is the local tool Housecall Pro is not.',
  },
  {
    slug: 'ascora',
    name: 'Ascora',
    tagline: 'Compare QuoteMate and Ascora for Australian tradie quoting and job management.',
    description: 'Ascora is an Australian-built job management and field-service platform for growing trade businesses, covering quoting, scheduling, invoicing, and strong local accounting and supplier integrations.',
    pricing: 'Ascora starts at $45/user/month (Essentials) and $59/user/month (Elite, most popular), with a one-time implementation fee on higher plans. 14-day free trial; no free plan.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: false },
      { name: 'Live Australian supplier pricing', quotemate: 'Bunnings, Reece, Tradelink', competitor: 'Reece price-file sync' },
      { name: 'Xero integration', quotemate: true, competitor: true },
      { name: 'MYOB integration', quotemate: false, competitor: true },
      { name: 'QuickBooks integration', quotemate: false, competitor: true },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: true },
      { name: 'Multi-crew dispatch & scheduling', quotemate: 'Google Calendar sync', competitor: true },
      { name: 'Equipment & custom forms', quotemate: false, competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'One-time setup fee', quotemate: 'None', competitor: 'On higher plans' },
      { name: 'Free plan available', quotemate: true, competitor: false },
      { name: 'Flat pricing (no per-user fees)', quotemate: '$49/month', competitor: 'Per-user' },
    ],
    summary: 'Ascora is a solid, genuinely Australian platform for trade businesses scaling toward multiple crews, and it has the strongest local accounting stack here — Xero, MYOB and QuickBooks. If you run MYOB or need multi-crew dispatch, equipment tracking, and custom forms, Ascora is stickier. QuoteMate is aimed at the sole trader and small crew: faster AI quoting across multiple suppliers with voice-to-text, a free plan, no per-user fees, no setup charge, and Square tap-to-pay — the simpler, cheaper way to quote and get paid before you need a full multi-crew system.',
  },
  {
    slug: 'xero',
    name: 'Xero',
    tagline: 'Compare QuoteMate and Xero for tradie quoting, invoicing, and accounting.',
    description: 'Xero is the market-leading cloud accounting platform in Australia, covering the full ledger, bank reconciliation, GST and BAS, payroll, and basic quotes and invoices.',
    pricing: 'Xero plans run from about $35/month (Ignite, capped at 20 invoices) up to $130+/month for higher tiers. It is accounting software, not a trade quoting app; there is no free plan.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: false },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'On-site quoting from your phone', quotemate: 'Native app', competitor: 'Not built for it' },
      { name: 'Trade-specific templates', quotemate: true, competitor: false },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: false },
      { name: 'On-site job photos & checklists', quotemate: true, competitor: false },
      { name: 'Square tap-to-pay on-site', quotemate: true, competitor: 'Via third parties' },
      { name: 'Syncs to Xero', quotemate: 'One-tap sync', competitor: 'Is Xero' },
      { name: 'Full accounting ledger, BAS & payroll', quotemate: 'Syncs to Xero', competitor: true },
      { name: 'Invoice caps on entry plan', quotemate: 'None', competitor: '20/month on Ignite' },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'Xero is not really a competitor — it is a partner. It owns the books, your accountant relationship, GST and payroll, and QuoteMate syncs straight to it. What Xero does not do is on-site trade quoting: there is no AI materials list, no live supplier pricing, no job pipeline, and its entry plan caps invoices. QuoteMate is the front-of-van tool that feeds Xero. Quote fast on site with live Bunnings and Reece pricing, take the payment, and push a clean invoice into Xero without re-keying a thing.',
  },
  {
    slug: 'myob',
    name: 'MYOB',
    tagline: 'Compare QuoteMate and MYOB for tradie quoting and invoicing.',
    description: 'MYOB is a long-established Australian accounting suite spanning a sole-trader mobile app (Solo) through full accounting (Business and AccountRight), covering invoicing, GST and BAS, and payroll.',
    pricing: 'MYOB ranges from about $11/month (Solo, which does not do quotes) through Business Lite and Pro (around $315/year to $70/month) to AccountRight (about $165/month).',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: false },
      { name: 'Quotes on the entry plan', quotemate: true, competitor: 'Not in MYOB Solo' },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'On-site quoting from your phone', quotemate: 'Native app', competitor: 'Limited' },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: false },
      { name: 'On-site job photos & checklists', quotemate: true, competitor: false },
      { name: 'Square tap-to-pay on-site', quotemate: true, competitor: 'Solo only' },
      { name: 'Full accounting ledger, BAS & payroll', quotemate: 'Syncs to Xero', competitor: true },
      { name: 'Trade-specific templates', quotemate: true, competitor: false },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'MYOB is trusted Australian accounting software, but its tradie-facing product tells the story: MYOB Solo, the cheap mobile plan, cannot even create a quote. QuoteMate is quoting-first — AI materials lists, live supplier pricing, a full job pipeline, and Square tap-to-pay — where MYOB is books-first. They are complementary: quote and get paid in QuoteMate, keep the ledger and payroll in MYOB or Xero. If you are choosing one tool to actually win and price work on site, that is QuoteMate.',
  },
  {
    slug: 'quickbooks',
    name: 'QuickBooks',
    tagline: 'Compare QuoteMate and QuickBooks for tradie quoting and invoicing.',
    description: 'QuickBooks Online is Intuit\'s cloud accounting platform, localised for Australia with GST and BAS, invoicing, unlimited quotes on its entry plan, and project tracking on higher tiers.',
    pricing: 'QuickBooks Online AU runs from about $33/month (Simple Start, with unlimited quotes and invoices) to $125/month (Advanced), frequently discounted with introductory promos.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: false },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'Trade-specific templates', quotemate: true, competitor: false },
      { name: 'On-site quoting from your phone', quotemate: 'Native app', competitor: 'Limited' },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: 'Project tracking (Plus)' },
      { name: 'On-site job photos & checklists', quotemate: true, competitor: false },
      { name: 'Square tap-to-pay on-site', quotemate: true, competitor: 'Via third parties' },
      { name: 'Full accounting ledger, BAS & payroll', quotemate: 'Syncs to Xero', competitor: true },
      { name: 'Unlimited quotes & invoices on entry plan', quotemate: true, competitor: true },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'QuickBooks Online is capable accounting software and, unlike Xero\'s entry plan, it allows unlimited quotes and invoices low down. But it is still books-first: no AI materials list, no live supplier pricing, no trade job pipeline, and it is not built for quoting on site. QuoteMate handles the on-site quoting layer — describe the job, get a priced materials list from live Bunnings and Reece rates, send a branded PDF, take payment — and you keep QuickBooks or Xero for the accounting. Different jobs, and they work together.',
  },
  {
    slug: 'quotient',
    name: 'Quotient',
    tagline: 'Compare QuoteMate and Quotient for online quoting.',
    description: 'Quotient is a cross-industry online quoting tool for small businesses, offering customisable quote templates, online acceptance, view tracking, and follow-up emails.',
    pricing: 'Quotient is US$28/month (Solo, 1 user) or US$48/month (Team, 2–5 users), priced in US dollars. It is quoting only — no invoicing, payments, or job management.',
    features: [
      { name: 'AI-powered quoting (materials list)', quotemate: true, competitor: false },
      { name: 'Live Australian supplier pricing', quotemate: true, competitor: false },
      { name: 'Built for Australian tradies', quotemate: true, competitor: 'Generic / cross-industry' },
      { name: 'Priced in Australian dollars', quotemate: true, competitor: false },
      { name: 'Professional PDF quotes', quotemate: true, competitor: true },
      { name: 'Online quote acceptance', quotemate: true, competitor: true },
      { name: 'Invoicing', quotemate: true, competitor: false },
      { name: 'Take payment on the quote', quotemate: 'Square tap-to-pay', competitor: false },
      { name: '9-stage job pipeline (inquiry to paid)', quotemate: true, competitor: false },
      { name: 'Automatic GST & ABN handling', quotemate: true, competitor: false },
      { name: 'Voice-to-text quoting', quotemate: true, competitor: false },
      { name: 'Free plan available', quotemate: true, competitor: false },
    ],
    summary: 'Quotient is a clean online quoting tool, but it is cross-industry, priced in US dollars, and stops at the quote — no invoicing, no payments, no job management, and no Australian supplier pricing or GST. QuoteMate is purpose-built for Australian tradies and covers the whole loop: AI materials lists priced against live Bunnings, Reece and Tradelink rates, a branded PDF, online acceptance, one-tap invoicing, Square tap-to-pay, and automatic GST — on a flat $49/month with a free plan.',
  },
];

export function getCompetitorBySlug(slug: string): Competitor | undefined {
  return competitors.find(c => c.slug === slug);
}

import compareContentRaw from '@/seo/compare-content.json';

export interface CompareContent {
  intro: string;
  sections: { heading: string; body: string }[];
  faqs?: { question: string; answer: string }[];
}

const compareContent = compareContentRaw as Record<string, CompareContent>;

export function getCompareContent(slug: string): CompareContent | undefined {
  return compareContent[slug];
}

export function getCompareHubContent(): CompareContent | undefined {
  return compareContent['_hub'];
}
