features:
- buildpack-stack=ubuntu-22
domains:
- domain: quotemateapp.au
  type: PRIMARY
  zone: quotemateapp.au
- domain: www.quotemateapp.au
  type: ALIAS
  zone: quotemateapp.au
ingress:
  rules:
  - component:
      name: quotemate-web
    match:
      path:
        prefix: /
name: quotemate-website
region: syd
static_sites:
- build_command: npm install && npm run build
  github:
    branch: main
    deploy_on_push: true
    repo: Krank3n/QuoteMateAppWebsite
  name: quotemate-web
  output_dir: /out
  catchall_document: 404.html
  source_dir: /
