import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'QuoteMate Terms of Service. Read the terms and conditions for using our quoting and invoicing application.',
  alternates: { canonical: 'https://quotemateapp.au/terms' },
  openGraph: {
    title: 'Terms of Service — QuoteMate',
    url: 'https://quotemateapp.au/terms',
  },
};

export default function TermsPage() {
  return (
    <>
      <Header homeLinks />
      <main className="legal-page">
        <div className="container">
          <div className="legal-content">
            <h1>Terms of Service</h1>
            <p className="legal-date">Effective date: 1 March 2026</p>

            <p>Welcome to QuoteMate. These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the QuoteMate application, website, and related services (collectively, the &ldquo;Service&rdquo;) provided by QuoteMate (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;). By accessing or using the Service, you agree to be bound by these Terms.</p>

            <h2>1. Acceptance of Terms</h2>
            <p>By creating an account, downloading the application, or otherwise using our Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and our <Link href="/privacy">Privacy Policy</Link>. If you do not agree to these Terms, you must not use the Service.</p>
            <p>You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you are at least 18 years old and have the legal capacity to enter into these Terms.</p>

            <h2>2. Service Description</h2>
            <p>QuoteMate is a quoting and invoicing application designed for Australian tradespeople (&ldquo;tradies&rdquo;). The Service provides:</p>
            <ul>
              <li>AI-powered job analysis and material suggestions</li>
              <li>Real-time material pricing from third-party suppliers</li>
              <li>Professional quote and invoice generation (PDF)</li>
              <li>Cloud sync across multiple devices</li>
              <li>Invoice and payment tracking</li>
              <li>Business branding customisation</li>
            </ul>

            <h3>2.1 Pricing Accuracy</h3>
            <p>While we endeavour to provide accurate and up-to-date material pricing, we do not guarantee the accuracy, completeness, or currency of pricing information retrieved from third-party suppliers. Prices are indicative only, and you should verify all pricing before issuing quotes to your clients. QuoteMate is not responsible for any losses arising from inaccurate pricing data.</p>

            <h3>2.2 AI-Generated Content</h3>
            <p>The AI-powered features of QuoteMate provide suggestions for materials, quantities, and job specifications. These suggestions are generated by artificial intelligence and are intended as a guide only. You are solely responsible for reviewing, verifying, and approving all content before sending quotes or invoices to your clients.</p>

            <h2>3. User Accounts</h2>
            <h3>3.1 Account Registration</h3>
            <p>To use certain features of the Service, you must create an account. You agree to:</p>
            <ul>
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Maintain the security and confidentiality of your login credentials</li>
              <li>Accept responsibility for all activities that occur under your account</li>
              <li>Notify us immediately of any unauthorised use of your account</li>
            </ul>

            <h3>3.2 Account Responsibilities</h3>
            <p>You are responsible for all content you create, upload, or share through the Service, including quotes, invoices, client information, and business details. You must ensure that your use of the Service complies with all applicable laws and regulations.</p>

            <h2>4. Subscription and Billing</h2>
            <h3>4.1 Free Plan</h3>
            <p>QuoteMate offers a free plan with limited features, including up to 5 quotes per month. The free plan may be subject to additional limitations as described on our pricing page.</p>

            <h3>4.2 Pro Subscription</h3>
            <p>The Pro subscription provides access to additional features, including unlimited quotes and invoices. Pro subscriptions are available on a monthly or annual basis. Pricing is displayed in Australian Dollars (AUD) and includes GST where applicable.</p>

            <h3>4.3 Free Trial</h3>
            <p>We may offer a free trial period for the Pro subscription. At the end of the trial period, you will be charged the applicable subscription fee unless you cancel before the trial ends. You may only use one free trial per account.</p>

            <h3>4.4 Payment</h3>
            <p>Subscription payments are processed through the Apple App Store, Google Play Store, or our website payment processor, depending on your platform. By subscribing, you authorise recurring charges to your chosen payment method.</p>

            <h3>4.5 Cancellation</h3>
            <p>You may cancel your Pro subscription at any time. Upon cancellation:</p>
            <ul>
              <li>You will retain access to Pro features until the end of your current billing period</li>
              <li>Your account will revert to the Free plan at the end of the billing period</li>
              <li>No refunds will be provided for partial billing periods</li>
              <li>Your data will be preserved and accessible under the Free plan limitations</li>
            </ul>

            <h3>4.6 Price Changes</h3>
            <p>We reserve the right to change subscription prices. We will provide at least 30 days&rsquo; notice of any price changes. Continued use of the Service after a price change constitutes acceptance of the new pricing.</p>

            <h2>5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable law, regulation, or third-party rights</li>
              <li>Create fraudulent, misleading, or deceptive quotes or invoices</li>
              <li>Transmit viruses, malware, or other harmful code</li>
              <li>Attempt to gain unauthorised access to our systems or other users&rsquo; accounts</li>
              <li>Use automated systems (bots, scrapers) to access the Service without our permission</li>
              <li>Resell, redistribute, or sublicence the Service without authorisation</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>

            <h2>6. Intellectual Property</h2>
            <h3>6.1 Our Intellectual Property</h3>
            <p>The Service, including its design, code, features, branding, logos, and documentation, is owned by QuoteMate and protected by Australian and international intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of the Service without our written consent.</p>

            <h3>6.2 Your Content</h3>
            <p>You retain ownership of all content you create using the Service (quotes, invoices, business data, etc.). By using the Service, you grant us a limited, non-exclusive licence to store, process, and display your content solely for the purpose of providing the Service to you.</p>

            <h3>6.3 Feedback</h3>
            <p>If you provide feedback, suggestions, or ideas about the Service, you grant us the right to use such feedback without restriction or compensation to you.</p>

            <h2>7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by Australian law:</p>
            <ul>
              <li>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express or implied</li>
              <li>We do not warrant that the Service will be uninterrupted, error-free, or free from harmful components</li>
              <li>We are not liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service</li>
              <li>Our total liability for any claims arising from the Service shall not exceed the amount you paid for the Service in the 12 months preceding the claim</li>
              <li>We are not responsible for the accuracy of third-party pricing data, AI-generated suggestions, or any business decisions you make based on information provided by the Service</li>
            </ul>
            <p>Nothing in these Terms excludes or limits liability that cannot be excluded or limited under Australian Consumer Law.</p>

            <h2>8. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless QuoteMate and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including legal fees) arising from:</p>
            <ul>
              <li>Your use of the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any applicable law or third-party rights</li>
              <li>The content you create or share through the Service</li>
            </ul>

            <h2>9. Termination</h2>
            <h3>9.1 Termination by You</h3>
            <p>You may terminate your account at any time by contacting us or using the account deletion feature in the app. Upon termination, your right to use the Service will cease immediately.</p>

            <h3>9.2 Termination by Us</h3>
            <p>We may suspend or terminate your account at any time if:</p>
            <ul>
              <li>You breach any provision of these Terms</li>
              <li>We are required to do so by law</li>
              <li>We reasonably believe your account has been compromised</li>
              <li>We discontinue the Service (with reasonable notice)</li>
            </ul>

            <h3>9.3 Effect of Termination</h3>
            <p>Upon termination, we may delete your account and associated data in accordance with our <Link href="/privacy">Privacy Policy</Link>. We recommend exporting your data before terminating your account.</p>

            <h2>10. Dispute Resolution</h2>
            <p>If a dispute arises between you and QuoteMate, we encourage you to contact us first at <a href="mailto:hello@quotemateapp.au">hello@quotemateapp.au</a> to seek a resolution. If the dispute cannot be resolved informally, either party may refer the matter to mediation before pursuing other legal remedies.</p>

            <h2>11. Governing Law</h2>
            <p>These Terms are governed by and construed in accordance with the laws of the Commonwealth of Australia. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Australia.</p>

            <h2>12. General Provisions</h2>
            <h3>12.1 Entire Agreement</h3>
            <p>These Terms, together with the Privacy Policy, constitute the entire agreement between you and QuoteMate regarding the Service and supersede all prior agreements.</p>

            <h3>12.2 Severability</h3>
            <p>If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.</p>

            <h3>12.3 Waiver</h3>
            <p>Our failure to enforce any provision of these Terms shall not constitute a waiver of that provision or any other provision.</p>

            <h3>12.4 Assignment</h3>
            <p>You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights and obligations under these Terms without your consent.</p>

            <h2>13. Changes to These Terms</h2>
            <p>We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on our website and updating the effective date. Your continued use of the Service after changes are posted constitutes acceptance of the modified Terms.</p>

            <h2>14. Contact Us</h2>
            <p>If you have any questions about these Terms of Service, please contact us:</p>
            <ul>
              <li>Email: <a href="mailto:hello@quotemateapp.au">hello@quotemateapp.au</a></li>
              <li>Website: <a href="https://quotemateapp.au">quotemateapp.au</a></li>
            </ul>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
